FROM golang:1.15 as builder
ENV GOPATH /go
COPY . /go/src/tor-controller
WORKDIR /go/src/tor-controller
RUN go install -a ./cmd/controller-manager

FROM debian:buster
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update -qq && apt-get install -y ca-certificates
COPY --from=builder /go/bin/controller-manager /usr/local/bin
ENTRYPOINT ["/usr/local/bin/controller-manager"]
CMD ["--install-crds=false"]
