FROM golang:1.15 as builder
ENV GOPATH /go
COPY . /go/src/tor-controller
WORKDIR /go/src/tor-controller
RUN go install -a ./cmd/tor-local-manager

FROM debian:buster
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update -qq && apt-get install -y ca-certificates tor
WORKDIR /root/
COPY --from=builder /go/bin/tor-local-manager .
ENTRYPOINT ["./tor-local-manager"]
